name: Deploy To EC2

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 작성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: 실행 권한 부여하기
        run: chmod +x ./gradlew

      # 추후 코너 케이스까지 완벽 검증 끝나면(-x test) 제외
      - name: 빌드
        run: ./gradlew clean build -x test

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./spoteditor.jar

      - name: AWS Credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t spoteditor .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag spoteditor ${{ steps.login-ecr.outputs.registry }}/spoteditor:latest

      - name: ECR에 Docker 이미지 Push하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/spoteditor:latest

      - name: 압축하기
        run: tar -czvf $GITHUB_SHA.tar.gz spoteditor.jar appspec.yml scripts

      - name: S3에 프로젝트 폴더 업로드하기
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://spoteditor-deploy-s3/$GITHUB_SHA.tar.gz

      - name: Code Deploy를 활용해 EC2에 프로젝트 코드 배포
        run: aws deploy create-deployment
            --application-name spoteditor
            --deployment-config-name CodeDeployDefault.AllAtOnce
            --deployment-group-name spoteditor-production
            --s3-location bucket=spoteditor-deploy-s3,bundleType=tgz,key=$GITHUB_SHA.tar.gz
